# Generated by Django 2.2.28 on 2023-04-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
                ('color', models.CharField(max_length=256)),
                ('is_fluffy', models.BooleanField()),
            ],
        ),
    ]
